export const ALLOWED_TEMPLATE_FIELDS = [
  'company.name',
  'company.logo',
  'company.address',
  'company.phone',
  'company.email',
  'company.website',
  'company.gstin',
  'quotation.quotationNumber',
  'quotation.date',
  'quotation.validUntil',
  'quotation.referenceNumber',
  'quotation.subject',
  'customer.companyName',
  'customer.contactPerson',
  'customer.email',
  'customer.phone',
  'customer.address',
  'coverLetter.greeting',
  'coverLetter.kindAttention',
  'coverLetter.subject',
  'coverLetter.message',
  'coverLetter.closing',
  'items.table',
  'items.description',
  'items.specification',
  'items.quantity',
  'items.unit',
  'items.unitPrice',
  'items.discount',
  'items.tax',
  'items.total',
  'pricing.subtotal',
  'pricing.totalDiscount',
  'pricing.taxableAmount',
  'pricing.tax',
  'pricing.additionalCharges',
  'pricing.grandTotal',
  'notes',
  'paymentTerms',
  'deliveryTerms',
  'terms',
  'bankDetails',
  'signature.name',
  'signature.designation',
  'signature.image',
]

export const ALLOWED_ITEM_TABLE_COLUMNS = [
  'description',
  'specification',
  'quantity',
  'unit',
  'unitPrice',
  'discount',
  'tax',
  'total',
]

export const DEFAULT_ITEM_TABLE_COLUMNS = [
  { key: 'description', label: 'Description', width: 220 },
  { key: 'quantity', label: 'Qty', width: 40 },
  { key: 'unit', label: 'Unit', width: 40 },
  { key: 'unitPrice', label: 'Price', width: 80 },
  { key: 'total', label: 'Total', width: 80 },
]

export function isAllowedTemplateField(field) {
  return ALLOWED_TEMPLATE_FIELDS.includes(field)
}
